driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: debian-7.11
  - name: debian-8.9
  - name: debian-9.1

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[runit_test]
  - recipe[runit-other_test]
  attributes: {}

- name: service
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[runit_test::service]
  - recipe[runit-other_test]
  attributes: {}
